"""docs/RESULTS.md: the paper's breakdowns (per chair count, mirrored spatial pairs, per
common-sense scene, navigation criteria) with the paper's published numbers beside ours."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from .score import score_all

# Numbers reported by Li et al. 2026 (arXiv 2603.15624), as recovered from the paper text.
PAPER = {
    "overall": {  # task -> {model: accuracy}
        "counting": {"GPT-4o": 0.94, "Claude-3.5-Sonnet": 0.75, "LLaVA-v1.6-Mistral-7B": 0.44},
        "spatial": {"GPT-4o": 1.00, "Claude-3.5-Sonnet": 0.57, "LLaVA-v1.6-Mistral-7B": 0.62},
        "commonsense": {
            "GPT-4o": 0.80,
            "Gemini-1.5-Pro": 0.63,
            "LLaVA-v1.6-Mistral-7B": 0.22,
            "LLaVA-OneVision-7B": 0.22,
        },
    },
    "per_count": {  # chairs -> {model: accuracy}
        1: {"GPT-4o": 1.00, "Gemini-1.5-Pro": 0.99, "Claude-3.5-Sonnet": 1.00},
        2: {"GPT-4o": 1.00, "Gemini-1.5-Pro": 0.99, "Claude-3.5-Sonnet": 1.00},
        3: {"GPT-4o": 1.00, "Gemini-1.5-Pro": 0.07, "Claude-3.5-Sonnet": 0.00},
        4: {"GPT-4o": 0.98, "Gemini-1.5-Pro": 0.45, "Claude-3.5-Sonnet": 1.00},
        6: {"GPT-4o": 0.92, "Gemini-1.5-Pro": 0.25, "Claude-3.5-Sonnet": 1.00},
    },
    "navigation": {  # model -> (destination, route, obstacles)
        "GPT-4o": (0.81, 0.92, 0.84),
        "Claude-3.5-Sonnet": (0.85, 0.87, 0.82),
        "Gemini-1.5-Pro": (0.30, 0.13, 0.64),
    },
}


def _load_runs(runs_root: Path, questions: dict) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for d in sorted(p for p in Path(runs_root).iterdir() if p.is_dir()):
        rows = []
        for task in ("counting", "spatial", "commonsense"):
            f = d / f"{task}.jsonl"
            if f.exists():
                rows += [json.loads(line) for line in f.read_text().splitlines() if line.strip()]
        rows = [r for r in rows if r["qid"] in questions]
        if rows:
            out[d.name] = rows
    return out


def _acc_by(rows_by_model: dict[str, list[dict]], questions: dict, task: str, keyf) -> dict:
    """{key: {model: accuracy}} for one task, key from keyf(question)."""
    table: dict = defaultdict(dict)
    for model, rows in rows_by_model.items():
        buckets: dict = defaultdict(lambda: [0, 0])
        for r in rows:
            q = questions[r["qid"]]
            if q["task"] != task or q.get("tier", "paper") != "paper":
                continue
            b = buckets[keyf(q)]
            b[0] += r["parsed"] == q["answer"]
            b[1] += 1
        for k, (c, n) in buckets.items():
            table[k][model] = round(c / n, 3)
    return dict(table)


def count_table(rows_by_model, questions):
    return _acc_by(rows_by_model, questions, "counting", lambda q: q["answer"])


def spatial_table(rows_by_model, questions):
    return _acc_by(rows_by_model, questions, "spatial", lambda q: q["scene"])


def scene_table(rows_by_model, questions, task):
    return _acc_by(rows_by_model, questions, task, lambda q: q["scene"])


def _md(table: dict, ours: list[str], paper: dict | None, first: str) -> list[str]:
    paper_models = sorted({m for v in (paper or {}).values() for m in v}) if paper else []
    head = (
        f"| {first} | "
        + " | ".join(ours)
        + (" | " + " | ".join(f"{m} (paper)" for m in paper_models) if paper_models else "")
        + " |"
    )
    lines = [head, "|---|" + "---|" * (len(ours) + len(paper_models))]
    keys = sorted(set(table) | set(paper or {}), key=lambda k: (isinstance(k, str), k))
    for k in keys:
        cells = [
            f"{table.get(k, {}).get(m, float('nan')):.0%}" if m in table.get(k, {}) else "–"
            for m in ours
        ]
        cells += [
            f"{(paper or {}).get(k, {}).get(m):.0%}"
            if (paper or {}).get(k, {}).get(m) is not None
            else "–"
            for m in paper_models
        ]
        lines.append(f"| {k} | " + " | ".join(cells) + " |")
    return lines


def write_report(runs_root: Path, questions: dict, out: Path) -> Path:
    rows_by_model = _load_runs(runs_root, questions)
    ours = sorted(rows_by_model)
    scored = score_all(runs_root, questions)
    L = [
        "# Results",
        "",
        "Generated by `nav report`. Paper tier only; accuracy over all repeats. "
        "Paper columns are the numbers published by Li et al. (2026) on their own runs.",
        "",
    ]
    L += ["## Overall accuracy", ""]
    overall = {
        t: {m: scored[m]["by_task"][t]["accuracy"] for m in ours if t in scored[m]["by_task"]}
        for t in ("counting", "spatial", "commonsense")
    }
    L += _md(overall, ours, PAPER["overall"], "task") + [""]
    L += (
        ["## Counting, by number of chairs", ""]
        + _md(count_table(rows_by_model, questions), ours, PAPER["per_count"], "chairs")
        + [""]
    )
    L += (
        ["## Spatial reasoning, by case (mirrored pairs test side bias)", ""]
        + _md(spatial_table(rows_by_model, questions), ours, None, "case")
        + [""]
    )
    L += (
        ["## Common-sense vacant seat, by scene", ""]
        + _md(scene_table(rows_by_model, questions, "commonsense"), ours, None, "scene")
        + [""]
    )
    judged = Path(runs_root) / "judged.jsonl"
    nav: dict[str, dict] = {}
    judges: set[str] = set()
    if judged.exists():
        by: dict[str, list] = defaultdict(list)
        for line in judged.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                by[r["model"]].append(r)
        for m, rs in by.items():
            nav[m] = {
                c: round(
                    sum(bool(r["ratings"][c]) for r in rs if r["ratings"].get(c) is not None)
                    / max(1, sum(1 for r in rs if r["ratings"].get(c) is not None)),
                    3,
                )
                for c in ("destination", "route", "obstacles")
            }
            nav[m]["n"] = len(rs)
            judges.update(r.get("judge_model", "?") for r in rs)
    who = ", ".join(sorted(judges)) if judges else "no judge run yet"
    L += [
        f"## Navigation, three criteria (judge: {who}; paper: two human annotators)",
        "",
        "| model | outputs | destination | route | obstacles |",
        "|---|---|---|---|---|",
    ]
    for m, v in nav.items():
        L.append(
            f"| {m} | {v['n']} | {v['destination']:.0%} | {v['route']:.0%} | {v['obstacles']:.0%} |"
        )
    for m, (d, r, o) in PAPER["navigation"].items():
        L.append(f"| {m} (paper) | 390 | {d:.0%} | {r:.0%} | {o:.0%} |")
    L.append("")
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    return out
